# Generated by Django 4.2.1 on 2023-05-28 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLibrarys',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular game across whole library', primary_key=True, serialize=False)),
                ('time_add', models.DateField(blank=True, null=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('game_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.games')),
            ],
            options={
                'ordering': ['time_add'],
            },
        ),
    ]
